# Generated by Django 3.2.9 on 2022-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
